# Тема “Вычисления с помощью Numpy”

## Задание 1

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

### Решение:

In [1]:
# Импорт библиотеки numpy
import numpy as np

In [2]:
# Создание массива a размером 5x2
a = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

In [3]:
# Нахождение среднего значения по каждому признаку
mean_a = a.mean(axis=0)

In [4]:
# Вывод массива mean_a
mean_a

array([2. , 8.4])

## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

### Решение:

In [5]:
# Вычисление массива a_centered
a_centered = a - mean_a

In [6]:
# Вывод массива a_centered
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

### Решение:

In [7]:
# Вычисление скалярного произведения столбцов массива a_centered
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [8]:
# Вывод массива a_centered_sp
a_centered_sp

8.0

In [9]:
# Число наблюдений
N = a.shape[0]

In [10]:
# Вывод числа наблюдений
N

5

In [11]:
# Деление скалярного произведения на N-1
result = a_centered_sp / (N - 1)

In [12]:
# Вывод результата
result

2.0

## Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:

[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

### Решение:

In [13]:
# Вычисление ковариационной матрицы с помощью функции np.cov
cov_matrix = np.cov(a.T)

In [14]:
# Вывод ковариационной матрицы, вычисленного с помощью np.cov
cov_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [15]:
# Извлечение значения ковариации из ковариационной матрицы
cov_value = cov_matrix[0, 1]

In [16]:
# Вывод значения ковариации, вычисленного с помощью np.cov
cov_value

2.0

# Тема “Работа с данными в Pandas”

## Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:

[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']

[500, 400, 300, 350, 450, 600, 200]

### Решение:

In [17]:
# Импорт библиотеки Pandas
import pandas as pd

In [18]:
# Создание DataFrame authors
authors_data = {
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(authors_data)

In [19]:
# Создание DataFrame book
books_data = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [500, 400, 300, 350, 450, 600, 200]
}
books = pd.DataFrame(books_data)

In [20]:
# Вывод DataFrame authors
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [21]:
# Вывод DataFrame book
books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

## Задание 2

Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

### Решение:

In [22]:
# Объединение DataFrame authors и books по полю author_id
authors_price = pd.merge(authors, books, on='author_id')

In [23]:
# Вывод DataFrame authors_price
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

## Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

### Решение:

In [24]:
# Создание DataFrame top5 с пятью самыми дорогими книгами
top5 = authors_price.nlargest(5, 'price')

In [25]:
# Вывод DataFrame top5
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

## Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:

author_name, min_price, max_price и mean_price,

в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.

### Решение:

In [26]:
# Группировка по автору и вычисление min, max и mean цены
authors_stat = authors_price.groupby('author_name').agg(
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    mean_price=('price', 'mean')
).reset_index()

In [27]:
# Вывод DataFrame authors_stat
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        200        600       400.0
1    Тургенев        300        500       400.0
2       Чехов        350        450       400.0

## Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

### Решение:

In [28]:
# Добавление нового столбца cover
covers = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price['cover'] = covers

In [29]:
# Вывод DataFrame authors_price
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [30]:
# Просмотр документации по функции pd.pivot_table
pd.pivot_table?

In [31]:
# Использование функции pd.pivot_table для вычисления суммарной стоимости книг с различными обложками
book_info = pd.pivot_table(
    authors_price,
    values='price',
    index='author_name',
    columns='cover',
    aggfunc='sum',
    fill_value=0
).reset_index().rename_axis(None, axis=1)

In [32]:
# Вывод DataFrame book_info
book_info

author_name  мягкая  твердая
0  Островский     800        0
1    Тургенев     700      500
2       Чехов       0      800

In [33]:
# Сохранение DataFrame book_info в формат pickle
book_info.to_pickle('book_info.pkl')

In [34]:
# Загрузка DataFrame из файла pickle
book_info2 = pd.read_pickle('book_info.pkl')

In [35]:
# Проверка идентичности DataFrame book_info и book_info2
book_info.equals(book_info2)

True

In [36]:
# Вывод DataFrame book_info
book_info

author_name  мягкая  твердая
0  Островский     800        0
1    Тургенев     700      500
2       Чехов       0      800

In [37]:
# Вывод DataFrame book_info2
book_info2

author_name  мягкая  твердая
0  Островский     800        0
1    Тургенев     700      500
2       Чехов       0      800